version: "3.7"
services:
  charalarm-localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs,sns,dynamodb
      - DEFAULT_REGION=ap-northeast-1
    volumes:
      - ./localstack/createQueue.sh:/docker-entrypoint-initaws.d/createQueue.sh
      - ./localstack/createTable.sh:/docker-entrypoint-initaws.d/createTable.sh
