name: CharacterAlarm
options:
  deploymentTarget:
    iOS: 13.0
  postGenCommand: bundle exec pod install


schemes:
  Local:
    build:
      targets:
        CharacterAlarm: all
    run:
      config: Debug
  Develop:
    build:
      targets:
        CharacterAlarm: all
    run:
      config: Debug
  Production:
    build:
      targets:
        CharacterAlarm: all
    run:
      config: Debug




targets:
  CharacterAlarm:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources:
      - CharacterAlarm
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: CharacterAlarm/CharacterAlarmRelease.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.swiswiswift.CharacterAlarm
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 5RH346BQ66
        INFOPLIST_FILE: CharacterAlarm/Info.plist
        MARKETING_VERSION: 2.0.0
        CURRENT_PROJECT_VERSION: 61
        TARGETED_DEVICE_FAMILY: 1
      configs:
        Debug:
          CODE_SIGN_ENTITLEMENTS: CharacterAlarm/CharacterAlarmDebug.entitlements
        Release:
          CODE_SIGN_ENTITLEMENTS: CharacterAlarm/CharacterAlarmRelease.entitlements
  # CharacterAlarmTests:
  #   type: bundle.unit-test
  #   platform: iOS
  #   sources:
  #     - CharacterAlarmTests
  #   settings:
  #     base:
  #       INFOPLIST_FILE: CharacterAlarmTests/Info.plist
  #   dependencies:
  #     - target: CharacterAlarm
  # CharacterAlarmUITests:
  #   type: bundle.ui-testing
  #   platform: iOS
  #   sources:
  #     - CharacterAlarmUITests
  #   settings:
  #     base:
  #       INFOPLIST_FILE: CharacterAlarmUITests/Info.plist
  #   dependencies:
  #     - target: CharacterAlarm
