name: Charalarm
options:
  deploymentTarget:
    iOS: 16.0
settings:
  base:
    MARKETING_VERSION: 3.4.1
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: 5RH346BQ66
    CURRENT_PROJECT_VERSION: 1
    TARGETED_DEVICE_FAMILY: 1
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES

packages:
  SDWebImageSwiftUI:
    url: https://github.com/SDWebImage/SDWebImageSwiftUI
    from: 2.2.1
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess
    from: 4.2.2
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: 11.3.0
  Datadog:
    url: https://github.com/Datadog/dd-sdk-ios.git
    from: 2.13.0
  Rswift:
    url: https://github.com/mac-cain13/R.swift
    from: 7.5.0
  GoogleMobileAds:
    url: https://github.com/googleads/swift-package-manager-google-mobile-ads
    from: 11.2.0

schemes:
  Develop:
    build:
      targets:
        CharalarmDevelop: all
    run:
      config: Debug
    # test:
    #   config: Debug
    #   gatherCoverageData: false
    #   targets:
    #     - name: CharalarmTests
    #       parallelizable: true
    #       randomExecutionOrder: true
  Staging:
    build:
      targets:
        CharalarmStaging: all
    run:
      config: Debug
  Production:
    build:
      targets:
        CharalarmProduction: all
    run:
      config: Debug

targets:
  CharalarmDevelop:
    type: application
    platform: iOS
    sources:
      - path: Charalarm
        excludes:
          - Charalarm/Resource
      - path: Charalarm/Resource
        type: folder
      - path: Config/Develop
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: Charalarm/CharalarmRelease.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.swiswiswift.sandbox.charalarm
        INFOPLIST_FILE: Charalarm/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon-Develop
        # OTHER_LDFLAGS:
        #   - $(inherited)
        #   - $(OTHER_LDFLAGS)
        #   - -ObjC
      configs:
        Debug:
          CODE_SIGN_ENTITLEMENTS: Charalarm/CharalarmDebug.entitlements
          API_ENDPOINT: https://api.charalarm-development.swiswiswift.com
          RESOURCE_ENDPOINT: https://resource.charalarm-development.swiswiswift.com
          GAD_APPLICATION_IDENTIFER: ca-app-pub-3940256099942544~1458002511
          ADMOB_ALARM_LIST: ca-app-pub-3940256099942544/2934735716
          ADMOB_CONFIG: ca-app-pub-3940256099942544/2934735716
          SUBSCRIPTION_PRODUCT_ID: charalarm.development.monthly.subscription
          DATADOG_CLIENT_TOKEN: pub2bd816c3d9d7157b4e1fd5febf77951f
          DATADOG_LOG_ENV: charalarm-development
          DATADOG_LOG_SERVICE: charalarm-development
        Release:
          CODE_SIGN_ENTITLEMENTS: Charalarm/CharalarmRelease.entitlements
          API_ENDPOINT: https://api.charalarm-development.swiswiswift.com
          RESOURCE_ENDPOINT: https://resource.charalarm-development.swiswiswift.com
          GAD_APPLICATION_IDENTIFER: ca-app-pub-3940256099942544~1458002511
          ADMOB_ALARM_LIST: ca-app-pub-3940256099942544/2934735716
          ADMOB_CONFIG: ca-app-pub-3940256099942544/2934735716
          SUBSCRIPTION_PRODUCT_ID: charalarm.development.monthly.subscription
          DATADOG_CLIENT_TOKEN: pub2bd816c3d9d7157b4e1fd5febf77951f
          DATADOG_LOG_ENV: charalarm-development
          DATADOG_LOG_SERVICE: charalarm-development
    dependencies:
      - sdk: AdSupport.framework
      - sdk: AppTrackingTransparency.framework
      - sdk: StoreKit.framework
      - package: Datadog
        product: DatadogCore
      - package: Datadog
        product: DatadogLogs
      - package: Firebase
        product: FirebaseAnalytics
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseCrashlytics
      - package: Firebase
        product: FirebaseFirestore
      - package: Firebase
        product: FirebaseRemoteConfig
      - package: KeychainAccess
        product: KeychainAccess
      - package: SDWebImageSwiftUI
        product: SDWebImageSwiftUI
      - package: Rswift
        product: RswiftLibrary
      - package: GoogleMobileAds
        product: GoogleMobileAds
    buildToolPlugins:
      - plugin: RswiftGenerateInternalResources
        package: Rswift
  CharalarmStaging:
    type: application
    platform: iOS
    sources:
      - path: Charalarm
        excludes:
          - Charalarm/Resource
      - path: Charalarm/Resource
        type: folder
      - path: Config/Staging
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: Charalarm/CharalarmRelease.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.charalarm.staging
        INFOPLIST_FILE: Charalarm/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon-Staging
        # OTHER_LDFLAGS:
        #   - $(inherited)
        #   - $(OTHER_LDFLAGS)
        #   - -ObjC
      configs:
        Debug:
          CODE_SIGN_ENTITLEMENTS: Charalarm/CharalarmDebug.entitlements
          API_ENDPOINT: https://api.charalarm.swiswiswift.com
          RESOURCE_ENDPOINT: https://resource.charalarm.swiswiswift.com
          GAD_APPLICATION_IDENTIFER: ca-app-pub-3940256099942544~1458002511
          ADMOB_ALARM_LIST: ca-app-pub-3940256099942544/2934735716
          ADMOB_CONFIG: ca-app-pub-3940256099942544/2934735716
          SUBSCRIPTION_PRODUCT_ID: charalarm.staging.monthly.subscription
          DATADOG_CLIENT_TOKEN: pub8e7e9ddd556eb859180ccad19517dd5c
          DATADOG_LOG_ENV: charalarm-staging
          DATADOG_LOG_SERVICE: charalarm-staging
        Release:
          CODE_SIGN_ENTITLEMENTS: Charalarm/CharalarmRelease.entitlements
          API_ENDPOINT: https://api.charalarm.swiswiswift.com
          RESOURCE_ENDPOINT: https://resource.charalarm.swiswiswift.com
          GAD_APPLICATION_IDENTIFER: ca-app-pub-3940256099942544~1458002511
          ADMOB_ALARM_LIST: ca-app-pub-3940256099942544/2934735716
          ADMOB_CONFIG: ca-app-pub-3940256099942544/2934735716
          SUBSCRIPTION_PRODUCT_ID: charalarm.staging.monthly.subscription
          DATADOG_CLIENT_TOKEN: pub8e7e9ddd556eb859180ccad19517dd5c
          DATADOG_LOG_ENV: charalarm-staging
          DATADOG_LOG_SERVICE: charalarm-staging
    dependencies:
      - sdk: AdSupport.framework
      - sdk: AppTrackingTransparency.framework
      - sdk: StoreKit.framework
      - package: Datadog
        product: DatadogCore
      - package: Datadog
        product: DatadogLogs
      - package: Firebase
        product: FirebaseAnalytics
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseCrashlytics
      - package: Firebase
        product: FirebaseFirestore
      - package: Firebase
        product: FirebaseRemoteConfig
      - package: KeychainAccess
        product: KeychainAccess
      - package: SDWebImageSwiftUI
        product: SDWebImageSwiftUI
      - package: Rswift
        product: RswiftLibrary
      - package: GoogleMobileAds
        product: GoogleMobileAds
    buildToolPlugins:
      - plugin: RswiftGenerateInternalResources
        package: Rswift
    # preBuildScripts:
    #   - script: ./Scripts/BuildPhases/rswift.sh
    #     name: R.swift
    #     basedOnDependencyAnalysis: false
    #     outputFiles:
    #       - $SRCROOT/Charalarm/Generated/R.generated.swift
  CharalarmProduction:
    type: application
    platform: iOS
    sources:
      - path: Charalarm
        excludes:
          - Charalarm/Resource
      - path: Charalarm/Resource
        type: folder
      - path: Config/Production
    dependencies:
      - sdk: AdSupport.framework
      - sdk: AppTrackingTransparency.framework
      - sdk: StoreKit.framework
      - package: Datadog
        product: DatadogCore
      - package: Datadog
        product: DatadogLogs
      - package: Firebase
        product: FirebaseAnalytics
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseCrashlytics
      - package: Firebase
        product: FirebaseFirestore
      - package: Firebase
        product: FirebaseRemoteConfig
      - package: KeychainAccess
        product: KeychainAccess
      - package: SDWebImageSwiftUI
        product: SDWebImageSwiftUI
      - package: Rswift
        product: RswiftLibrary
      - package: GoogleMobileAds
        product: GoogleMobileAds
    buildToolPlugins:
      - plugin: RswiftGenerateInternalResources
        package: Rswift
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: Charalarm/CharalarmRelease.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.swiswiswift.CharacterAlarm
        INFOPLIST_FILE: Charalarm/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon-Production
        # OTHER_LDFLAGS:
        #   - $(inherited)
        #   - $(OTHER_LDFLAGS)
        #   - -ObjC
      configs:
        Debug:
          CODE_SIGN_ENTITLEMENTS: Charalarm/CharalarmDebug.entitlements
          API_ENDPOINT: https://api.charalarm.com
          RESOURCE_ENDPOINT: https://resource.charalarm.com
          GAD_APPLICATION_IDENTIFER: ca-app-pub-5587141252700968~9053558907
          ADMOB_ALARM_LIST: ca-app-pub-5587141252700968/8220227024
          ADMOB_CONFIG: ca-app-pub-5587141252700968/1355204268
          SUBSCRIPTION_PRODUCT_ID: charalarm.production.monthly.subscription
          DATADOG_CLIENT_TOKEN: pub746809c11c5291884508b5936605a3bf
          DATADOG_LOG_ENV: charalarm-production
          DATADOG_LOG_SERVICE: charalarm-production
        Release:
          CODE_SIGN_ENTITLEMENTS: Charalarm/CharalarmRelease.entitlements
          API_ENDPOINT: https://api.charalarm.com
          RESOURCE_ENDPOINT: https://resource.charalarm.com
          GAD_APPLICATION_IDENTIFER: ca-app-pub-5587141252700968~9053558907
          ADMOB_ALARM_LIST: ca-app-pub-5587141252700968/8220227024
          ADMOB_CONFIG: ca-app-pub-5587141252700968/1355204268
          SUBSCRIPTION_PRODUCT_ID: charalarm.production.monthly.subscription
          DATADOG_CLIENT_TOKEN: pub746809c11c5291884508b5936605a3bf
          DATADOG_LOG_ENV: charalarm-production
          DATADOG_LOG_SERVICE: charalarm-production
  # CharalarmTests:
  #   type: bundle.unit-test
  #   platform: iOS
  #   sources:
  #     - CharalarmTests
  #   settings:
  #     base:
  #       INFOPLIST_FILE: CharalarmTests/Info.plist
  #   dependencies:
  #     - target: CharalarmDevelop
  # CharalarmUITests:
  #   type: bundle.ui-testing
  #   platform: iOS
  #   sources:
  #     - CharalarmUITests
  #   settings:
  #     base:
  #       INFOPLIST_FILE: CharalarmUITests/Info.plist
  #   dependencies:
  #     - target: CharalarmDevelop
