# Staging環境でのCloudFrontのキャッシュを削除
name: Remove Cloudfront Cache For Staging

on:
  workflow_dispatch:

env:
  AWS_ROLE_ARN: arn:aws:iam::334832660826:role/charalarm-github-action-role
  LP_CLOUD_FRONT_DISTRIBUTION_ID: ECN9Z2VJIOP8L
  RESOURCE_CLOUD_FRONT_DISTRIBUTION_ID: E1KAAIDVM6F9GQ

jobs:
  test:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          role-session-name: charalarm-github-action-role-${{ github.run_id }} # CloudTrailイベントに表示されるユーザー名
          aws-region: ap-northeast-1

      - name: Delete Chaches for charalarm.sandbox.swiswiswift.com
        run: |
          aws cloudfront create-invalidation --distribution-id $LP_CLOUD_FRONT_DISTRIBUTION_ID --paths "/*"

      - name: Delete Chaches for resource.charalarm.sandbox.swiswiswift.com
        run: |
          aws cloudfront create-invalidation --distribution-id $RESOURCE_CLOUD_FRONT_DISTRIBUTION_ID --paths "/*"
