name: Build for Application API Image

on:
  workflow_dispatch:

env:
  AWS_ROLE_ARN: arn:aws:iam::448049807848:role/charalarm-github-action-role

jobs:
  build_api_image:
    name: build api image
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    # チェックアウト
    - name: Checkout
      uses: actions/checkout@v4


    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.AWS_ROLE_ARN }}
        role-session-name: github-action-role-${{ github.run_id }}
        aws-region: ap-northeast-1

    - name: configure aws profiles
      run: |
        mkdir ~/.aws
        cp .github/workflows/aws_config/config ~/.aws/config

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: linux/arm64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # - name: Build ARM64 Docker image
    #   working-directory: application/api
    #   run: |
    #     docker buildx create --use --platform linux/arm64
    #     docker buildx build --platform linux/arm64 -t charalarm-api .
    - name: build api image
      working-directory: application/api
      run: make build-image



    # # Go言語のセットアップ
    # - name: Set up Go
    #   uses: actions/setup-go@v5
    #   with:
    #     go-version: 1.21

    # # Mock環境のセットアップ
    # - name: Setup Mock
    #   working-directory: application/mock
    #   run: make setup

    # # Local Stack の起動完了まで待つ
    # - name: Wait SetUp Localstack
    #   run: sleep 30s

    # # Application API の実行
    # - name: Run Test
    #   env:
    #       AWS_ACCESS_KEY_ID: "dummy"
    #       AWS_SECRET_ACCESS_KEY: "dummy"
    #   working-directory: application/api
    #   run: make test
