name: CI for Application API

on:
  workflow_dispatch:
  pull_request:
    paths:
      - application/api/**
    branches: 
      - main
      - develop


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # チェックアウト
    - uses: actions/checkout@v4

