name: CI for Application API

on:
  workflow_dispatch:
  pull_request:
    paths:
      - application/api/**
    branches: 
      - main
      - develop


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # チェックアウト
    - name: Checkout
      uses: actions/checkout@v4

    # Mock環境のセットアップ
    - name: Setup Mock
      working-directory: application/mock
      run: make setup

    # Application API の実行
    - name: Run Test
      working-directory: application/api
      run: make test


