name: CI for Application API

on:
  workflow_dispatch:
  pull_request:
    paths:
      - application/api/**
    branches: 
      - main
      - develop


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # チェックアウト
    - uses: actions/checkout@v4

    # # mintのインストール
    # - name: Install Mint
    #   working-directory: ios
    #   run: brew install mint

    # # パッケージのインストール
    # - name: Mint Bootstrap
    #   working-directory: ios
    #   run: mint bootstrap

    # # swiftlintの実行
    # - name: Run SwiftLint
    #   working-directory: ios
    #   run: mint run swiftlint --strict
