name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ main, develop ]

env:
  DEVELOPER_DIR: /Applications/Xcode_15.0.1.app

jobs:
  build:
    runs-on: macos-13

    steps:
    # チェックアウト
    - uses: actions/checkout@v4

    # mintのインストール
    - name: Install Mint
      run: brew install mint

    # swiftlintの実行
    - name: Run SwiftLint
      run: mint run swiftlint --strict
