name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    # チェックアウト
    - uses: actions/checkout@v4

    # swiftlintの実行
    - name: Install Bundler
      run: mint run swiftlint --strict
