name: Deploy to Sandbox

on:
  workflow_dispatch:

env:
  APPLICATION_VERSION: 0.0.1
  S3_BUCKET_NAME: application.charalarm.sandbox.swiswiswift.com

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.2

      - name: Build
        run: |
          cd application && sh build.sh

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Deploy to S3
        run: |
          aws s3 sync application/build s3://$S3_BUCKET_NAME/$APPLICATION_VERSION --exact-timestamps --delete

      - name: Update Function Code
        run: |
          aws lambda update-function-code --function-name healthcheck-get-function --s3-bucket $S3_BUCKET_NAME --s3-key $APPLICATION_VERSION/healthcheck.zip
          aws lambda update-function-code --function-name user-signup-anonymous-post-function --s3-bucket $S3_BUCKET_NAME --s3-key $APPLICATION_VERSION/signup_anonymous_user.zip
          aws lambda update-function-code --function-name user-withdraw-anonymous-post-function --s3-bucket $S3_BUCKET_NAME --s3-key $APPLICATION_VERSION/withdraw_anonymous_user.zip
