# Development環境にWebAPIをデプロイ
name: Deploy For Development

on:
  workflow_dispatch:
  push:
    branches: [ develop ]

env:
  APPLICATION_VERSION: 0.0.1
  S3_BUCKET_NAME: application.charalarm.sandbox.swiswiswift.com

jobs:
  test:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::397693451628:role/charalarm-github-action-role
          role-session-name: charalarm-github-action-role-${{ github.run_id }} # CloudTrailイベントに表示されるユーザー名
          aws-region: ap-northeast-1

      - name: Build and Deploy
        run: |
          cd script && sh build-deploy.sh
