name: Development Deploy Batch
description: DevelopmentのBatchをデプロイする

on:
  workflow_dispatch:

env:
  APPLICATION_VERSION: 0.0.1
  S3_BUCKET_NAME: application.charalarm.sandbox.swiswiswift.com

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Update Function Code
        run: |
          aws lambda update-function-code --function-name batch-function --s3-bucket $S3_BUCKET_NAME --s3-key $APPLICATION_VERSION/batch.zip
