name: DevelopTest

on:
  workflow_dispatch:
  push:
    branches: [ develop ]

env:
  AWS_ACCESS_KEY_ID: dummy
  AWS_SECRET_ACCESS_KEY: dummy
  # AWS_DEFAULT_REGION: ap-nor

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.2

      - name: Set up Docker
        run: |
          cd application && docker-compose up -d

      - name: PWD
        run: |
          pwd

      - name: Test
        run: |
          cd application && sh test.sh
