name: Test for iOS

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ios/**
    branches: 
      - main
      - develop

env:
  DEVELOPER_DIR: /Applications/Xcode_15.0.1.app

jobs:
  test_ios:
    runs-on: macos-13

    steps:
    # チェックアウト
    - uses: actions/checkout@v4

    # mintのインストール
    - name: Install Mint
      working-directory: ios
      run: brew install mint

    # パッケージのインストール
    - name: Mint Bootstrap
      working-directory: ios
      run: mint bootstrap

    # swiftlintの実行
    - name: Run SwiftLint
      working-directory: ios
      run: mint run swiftlint --strict
