# Developブランチへのプルリクエストのテスト
name: TestPullRequestToDevelopBranch

on:
  workflow_dispatch:
  pull_request:
    branches: [ develop ]
env:
  AWS_ACCESS_KEY_ID: dummy
  AWS_SECRET_ACCESS_KEY: dummy

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.3

      - name: Set up Docker
        run: |
          cd localstack && docker-compose up -d

      - name: Wait for Set up Docker
        run: sleep 30

      - name: Test
        run: |
          cd script && sh test.sh
